import type { AdminCrudItem, AdminCrudResource } from "./contracts"

export const adminCrudMockResource: AdminCrudResource = {
  title: "Публикации",
  singularTitle: "публикацию",
  slug: "blog-posts",
  defaultView: "list",
  supportedViews: ["list", "cards", "kanban", "calendar", "timeline"],
  columns: [
    { key: "title", label: "Название" },
    { key: "status", label: "Статус" },
    { key: "rubrics", label: "Рубрики" },
    { key: "scheduledFor", label: "Публикация" },
    { key: "author", label: "Автор" },
  ],
}

export const adminCrudMockItems: AdminCrudItem[] = [
  {
    id: 101,
    title: "Как команда готовит релиз без героизма",
    slug: "release-without-heroics",
    status: "draft",
    caption: "Черновик статьи про операционный ритм продуктовой команды.",
    rubrics: ["Процессы", "Команда"],
    author: "Мария",
    readingTime: 7,
    scheduledFor: "2026-05-24T10:00:00+03:00",
  },
  {
    id: 102,
    title: "Пять UX-паттернов, которые экономят часы поддержки",
    slug: "ux-support-patterns",
    status: "in_review",
    caption: "Материал ждет редакторской проверки и согласования иллюстраций.",
    rubrics: ["UX", "SaaS"],
    author: "Илья",
    readingTime: 9,
    scheduledFor: "2026-05-25T12:30:00+03:00",
  },
  {
    id: 103,
    title: "Календарь публикаций как инструмент управления спросом",
    slug: "publication-calendar-demand",
    status: "scheduled",
    caption: "Запланированная публикация для блока контент-маркетинга.",
    rubrics: ["Маркетинг"],
    author: "Анна",
    readingTime: 6,
    scheduledFor: "2026-05-27T15:00:00+03:00",
  },
  {
    id: 104,
    title: "Почему внутреннюю дизайн-систему надо начинать с вертикальных наборов",
    slug: "vertical-kits-first",
    status: "published",
    caption: "Опубликованный материал про подход к стандартизации интерфейсов.",
    rubrics: ["Design System", "Frontend"],
    author: "Максим",
    readingTime: 11,
    scheduledFor: "2026-05-20T09:00:00+03:00",
  },
  {
    id: 105,
    title: "Архивный пост: старый подход к CMS",
    slug: "legacy-cms-approach",
    status: "archived",
    caption: "Архивная запись для проверки фильтра архива.",
    rubrics: ["Legacy"],
    author: "Команда",
    readingTime: 4,
    scheduledFor: "2026-05-18T09:00:00+03:00",
  },
  {
    id: 106,
    title: "Как читать метрики, если данных пока мало",
    slug: "low-data-analytics",
    status: "scheduled",
    caption: "Пример карточки с несколькими рубриками и будущей датой.",
    rubrics: ["Analytics", "ERP"],
    author: "Олег",
    readingTime: 8,
    scheduledFor: "2026-06-03T11:00:00+03:00",
  },
]
